[build]
    base = "/"
    publish = "/"

[[redirects]]
    from = "/trickOrTreat/*"
    to = "https://halloween-candy-request.netlify.app/trickOrTreat/:splat"
    status = 200

[[redirects]]
    from = "/chew/*"
    to = "https://chewapp.netlify.app/chew/:splat"
    status = 200